name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose build

      - name: Whereis docker-compose
        run: whereis docker-compose

      # First try
      - name: 1st try - First run
        run: docker-compose up -d

      - name: 1st try - Stop the stack
        run: docker-compose down

      - name: 1st try - Second again
        run: docker-compose up --exit-code-from test-tsx

      # 2nd try
      - name: 2nd try - First run
        run: docker-compose up -d

      - name: 2nd try - Stop the stack
        run: docker-compose down

      - name: 2nd try - Run again
        run: docker-compose up --exit-code-from test-tsx

      # 3rd try
      - name: 3rd try - First run
        run: docker-compose up -d

      - name: 3rd try - Stop the stack
        run: docker-compose down

      - name: 3rd try - Run again
        run: docker-compose up --exit-code-from test-tsx

      # 4th try
      - name: 4th try - First run
        run: docker-compose up -d

      - name: 4th try - Stop the stack
        run: docker-compose down

      - name: 4th try - Run again
        run: docker-compose up --exit-code-from test-tsx
