name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose build

      - name: Whereis docker-compose
        run: whereis docker-compose

      - name: First run
        run: docker-compose up

      - name: Run again
        run: docker-compose up

      - name: Run again
        run: docker-compose up

      - name: Run again
        run: docker-compose up

      - name: Run again
        run: docker-compose up

      - name: Run again
        run: docker-compose up

      - name: Run again
        run: docker-compose up
