name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose build
      - name: First run
        run: docker-compose up -d
      - name: Restart the stack
        run: docker-compose stop
      - name: Second run
        run: docker-compose up
